### ISSUE TITLE
Is it possible to build on freeswitch version 1.8.6?

### ISSUE THREAD

**Issue by 2954456878** [amigniter/mod_audio_stream#40]
/usr/local/src/freeswitch-1.8.6/src/mod/applications/mod_audio_stream/audio_streamer_glue.cpp: In function ‘switch_bool_t {anonymous}::filter_json_string(switch_core_session_t*, const char*)’:
/usr/local/src/freeswitch-1.8.6/src/mod/applications/mod_audio_stream/audio_streamer_glue.cpp:288:34: error: 'cJSON_IsString' has not been declared in this scope
if(cJSON_IsString(partial)) {
^
make[2]: *** [CMakeFiles/mod_audio_stream.dir/build.make:90: CMakeFiles/mod_audio_stream.dir/audio_streamer_glue.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mod_audio_stream.dir/all] Error 2
make: ***[Makefile:136:all] Error 2

**Comment by amigniter** [comment]
In file _audio_streamer_glue.cpp_ delete lines 15-17 and 278-306. It's not being used and you will build the module just fine in older FS version.
